from enum import Enum


class Snmpv3GroupTypeEnum(str, Enum):
    SGT_MANAGERPRIV = "SGT_MANAGERPRIV"
    SGT_MANAGERAUTH = "SGT_MANAGERAUTH"
    SGT_OPERATORAUTH = "SGT_OPERATORAUTH"
    SGT_OPERATORNOAUTH = "SGT_OPERATORNOAUTH"
    SGT_COMMANAGERRW = "SGT_COMMANAGERRW"
    SGT_COMMANAGERR = "SGT_COMMANAGERR"
    SGT_COMOPERATORRW = "SGT_COMOPERATORRW"
    SGT_COMOPERATORR = "SGT_COMOPERATORR"
    SGT_NONE = "SGT_NONE"

